# Copyright 2013-2022 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

import os.path
from textwrap import dedent

from spack.package import *


class LinuxPerf(Package):
    """The Linux perf tool."""

    homepage = "https://www.kernel.org/"
    url = "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.5.5.tar.xz"

    executables = ["^perf$"]

    version("6.5.7", sha256="0d09ea448005c9cfe5383e4c72a872b39188b928f8c44e146b03b1b7851fbb8c")
    version("6.1.58", sha256="ce987ed3d2f640b3a2a62a0a8573d538a36dfd3cc31e2d7a239ce5a16c1c21ad")
    version("5.15.135", sha256="14835e629e237f136cfed484fdb533c95242429809bdcdb2a2d66dfcb7447170")

    variant("libtraceevent", default=True, description="recommended dependency")
    variant("python", default=True, description="Python support")
    variant("perl", default=True, description="perl script extension")
    variant("slang", default=True, description="TUI support")
    variant("libpfm4", default=True, description="libpfm4 events extension")
    variant("babeltrace", default=True, description="libbabeltrace support for CTF data format")
    variant("libcap", default=True, description="process capabilities considered by perf")
    variant("numactl", default=True, description="numa perf benchmark")
    variant("debuginfod", default=False, description="support debuginfod")
    variant(
        "zstd",
        default=True,
        description="Zstandard based runtime trace compression in record mode",
    )
    variant("xz", default=True, description="xz kernel module decompression")
    variant(
        "openssl",
        default=True,
        description="support generating build-ids for ELFs generated by jitdump",
    )
    variant("jvmti", default=False, description="build jvmti agent")

    depends_on("gmake", type="build")
    depends_on("pkgconfig", type="build")
    depends_on("flex", type="build")
    depends_on("bison", type="build")

    depends_on("elfutils")
    depends_on("elfutils +debuginfod", when="+debuginfod")
    depends_on("libunwind components=ptrace")
    depends_on("libiberty")
    depends_on("binutils", type=("build", "link", "run"))
    depends_on("zlib")

    depends_on("libtraceevent", when="+libtraceevent")

    # jevents requires python >= 3.6
    depends_on("python@3.6:", type=("build", "link", "run"), when="+python")
    depends_on("py-setuptools", type="build", when="+python")
    depends_on("perl", when="+perl")
    depends_on("slang", when="+slang")
    depends_on("libpfm4", when="+libpfm4")
    depends_on("babeltrace@1.5:", when="+babeltrace")
    depends_on("libcap", when="+libcap")
    depends_on("numactl", when="+numactl")
    depends_on("zstd", when="+zstd")
    depends_on("xz", when="+xz")
    depends_on("openssl", when="+openssl")
    depends_on("java", when="+jvmti")

    depends_on("asciidoc", type="build")
    depends_on("xmlto", type="build")

    conflicts(
        "~libtraceevent",
        when="@6.2:",
        msg="linux 6.2 removed internal libtraceevent, and it's highly recommended",
    )

    def url_for_version(self, version):
        return f"https://cdn.kernel.org/pub/linux/kernel/v{version[0]}.x/linux-{version}.tar.xz"

    def setup_build_environment(self, env):
        # This variable is used in the Makefile. If it is defined on the
        # system, it can break the build if there is no build recipe for
        # that specific ARCH
        env.unset("ARCH")

    @property
    def archive_files(self):
        return [join_path(self.stage.source_path, "tools/perf/FEATURE-DUMP")]

    def install(self, spec, prefix):
        # TODO:
        # - GTK2=
        # - NO_LIBAUDIT=1 when NO_SYSCALL_TABLE=1 ?
        # - NO_LIBBPF=1
        # - d3 flamegraph as resource for libexec/perf-core/scripts/python/flamegraph.py
        # - elfutils could be replaced by libelf ? (NO_LIBELF NO_LIBDWARF NO_LIBUNWIND etc.)

        # Note:
        #
        # The majority of "NO_*" are tested using ifdef/indef and not if/eq/neq.
        # i.e. NO_LIBPYTHON=0/1/foobar will all disable libpython.
        #
        # This also means there is no trivial way to force a dependency (for most of them).

        version = self.spec.version

        args = [
            "LIBDW_DIR={}".format(spec["elfutils"].prefix),
            "LIBUNWIND_DIR={}".format(spec["libunwind"].prefix),
        ]

        if version >= Version("6.4"):
            args.append("BUILD_NONDISTRO=1")

        if "+debuginfod" in spec:
            pass
        else:
            args.append("NO_LIBDEBUGINFOD=1")

        if "+python" in spec:
            args.extend(
                [
                    "PYTHON={}".format(spec["python"].command),
                    "PYTHON_CONFIG={}".format(spec["python"].prefix.bin.join("python-config")),
                ]
            )
        else:
            args.append("NO_LIBPYTHON=1")

        if "+perl" in spec:
            pass
        else:
            args.append("NO_LIBPERL=1")

        if "+slang" in spec:
            pass
        else:
            args.append("NO_SLANG=1")

        if "+libpfm4" in spec:
            if version < Version("6.4"):
                args.append("LIBPFM4=1")
        else:
            if version >= Version("6.4"):
                args.append("NO_LIBPFM4=1")

        if "+babeltrace" in spec:
            args.append("LIBBABELTRACE_DIR={}".format(spec["babeltrace"].prefix))
        else:
            args.append("NO_LIBBABELTRACE=1")

        if "+libcap" in spec:
            pass
        else:
            args.append("NO_LIBCAP=1")

        if "+numactl" in spec:
            pass
        else:
            args.append("NO_LIBNUMA=1")

        if "+xz" in spec:
            pass
        else:
            args.append("NO_LZMA=1")

        if "+zstd" in spec:
            args.append("LIBZSTD_DIR={}".format(spec["zstd"].prefix))
        else:
            args.append("NO_LIBZSTD=1")

        if "+libtraceevent" in spec:
            if version < Version("6.2"):
                args.append("LIBTRACEEVENT_DYNAMIC=1")
        else:
            if version >= Version("6.2"):
                args.append("NO_LIBTRACEEVENT=1")

        if "+jvmti" in spec:
            args.append("JDIR={}".format(spec["java"].prefix))
        else:
            args.append("NO_JVMTI=1")

        with working_dir("tools/perf"):
            make(
                "V=1",
                f"JOBS={make_jobs}",
                f"prefix={prefix}",
                "DESTDIR=",
                *args,
                "all",
                "install",
                parallel=False,
            )

        # Create a perfconfig with binutils paths
        perfconfig = str(prefix.join("etc/perfconfig"))
        assert not os.path.exists(perfconfig)
        mkdirp(os.path.dirname(perfconfig))
        with open(perfconfig, "w") as f:
            f.write(
                dedent(
                    """\
                    [annotate]
                    addr2line = {addr2line}
                    objdump = {objdump}
                    """
                ).format(
                    addr2line=spec["binutils"].prefix.bin.join("addr2line"),
                    objdump=spec["binutils"].prefix.bin.join("objdump"),
                )
            )
