version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Requirements to build documentation
  - package-ecosystem: "pip"
    directory: "/lib/spack/docs"
    schedule:
      interval: "daily"
  # Requirements to run style checks
  - package-ecosystem: "pip"
    directory: "/.github/workflows/style"
    schedule:
      interval: "daily"
