version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directories:
     - "/.github/workflows/requirements/*"
     - "/lib/spack/docs"
    schedule:
      interval: "daily"
