lib/spack/docs/packaging_guide.rst
lib/spack/spack/test/environment_modifications.py
lib/spack/spack/test/util/environment.py
lib/spack/spack/util/environment.py
var/spack/repos/builtin/packages/acl/package.py
var/spack/repos/builtin/packages/atop/package.py
var/spack/repos/builtin/packages/bcache/package.py
var/spack/repos/builtin/packages/cppunit/package.py
var/spack/repos/builtin/packages/diffutils/package.py
var/spack/repos/builtin/packages/emacs/package.py
var/spack/repos/builtin/packages/f77-zmq/package.py
var/spack/repos/builtin/packages/fgsl/package.py
var/spack/repos/builtin/packages/fish/package.py
var/spack/repos/builtin/packages/ganglia/package.py
var/spack/repos/builtin/packages/git/package.py
var/spack/repos/builtin/packages/intel-llvm/package.py
var/spack/repos/builtin/packages/ldak/package.py
var/spack/repos/builtin/packages/lhapdf5/package.py
var/spack/repos/builtin/packages/libmesh/package.py
var/spack/repos/builtin/packages/libxc/package.py
var/spack/repos/builtin/packages/libxpm/package.py
var/spack/repos/builtin/packages/llvm/package.py
var/spack/repos/builtin/packages/lmbench/package.py
var/spack/repos/builtin/packages/metis/package.py
var/spack/repos/builtin/packages/mysql/package.py
var/spack/repos/builtin/packages/nfs-utils/package.py
var/spack/repos/builtin/packages/py-scikit-learn/package.py
var/spack/repos/builtin/packages/range-v3/gcc-compile-opt-check.patch
var/spack/repos/builtin/packages/ripgrep/package.py
var/spack/repos/builtin/packages/samrai/package.py
var/spack/repos/builtin/packages/sollve/package.py
var/spack/repos/builtin/packages/templight/package.py
var/spack/repos/builtin/packages/thrift/package.py
var/spack/repos/builtin/packages/trinity/package.py
var/spack/repos/builtin/packages/xrootd/package.py
var/spack/repos/builtin/packages/xsd/package.py
var/spack/repos/builtin/packages/zlib/package.py
var/spack/repos/builtin/packages/zstd/package.py
