# Copyright 2013-2019 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)



from spack import *


class PyMdanalysisMummi(PythonPackage):
    """MDAnalysis-MuMMI is the customization of MDAnalysis for MuMMI to 
    support DDCMD and DDCMD-TAR file formats.
    
    MDAnalysis is a Python toolkit to analyze molecular dynamics
    trajectories generated by a wide range of popular simulation
    packages including DL_Poly, CHARMM, Amber, NAMD, LAMMPS, and
    Gromacs. (See the lists of supported trajectory formats and
    topology formats.)"""

    homepage = "https://github.com/XiaohuaZhangLLNL/mdanalysis"

    version('mda_1.0.1_ddcmd', tag='mda_1.0.1_ddcmd', git='git@github.com:XiaohuaZhangLLNL/mdanalysis.git')
    version('mda_1.0.0_ddcmd', tag='mda_1.0.0_ddcmd', git='git@github.com:XiaohuaZhangLLNL/mdanalysis.git')
    version('mda_1.0.3_ddcmd', tag='mda_1.0.3_ddcmd', git='git@github.com:XiaohuaZhangLLNL/mdanalysis.git')
    version('mda_1.0.4_ddcmd', tag='mda_1.0.4_ddcmd', git='git@github.com:XiaohuaZhangLLNL/mdanalysis.git')

    build_directory = 'package'

    depends_on('python@3:')
    depends_on('py-setuptools', type='build')
    depends_on('py-cython@0.16:', type='build')

    depends_on('py-numpy@1.5.0:', type=('build', 'run'))
    depends_on('py-scipy@1.0.0:', type=('build', 'run'))

    depends_on('py-six@1.4.0:',      type=('build', 'run'))
    depends_on('py-networkx@1.0:',   type=('build', 'run'))
    depends_on('py-biopython@1.71:', type=('build', 'run'))

    depends_on('py-gsd@1.4.0:',         type=('build', 'run'))
    depends_on('py-mmtf-python@1.0.0:', type=('build', 'run'))
    depends_on('py-mock',               type=('build', 'run'))
    depends_on('py-tqdm@4.43.0:',       type=('build', 'run'))
    depends_on('py-joblib@0.12:',       type=('build', 'run'))
    depends_on('py-griddataformats@0.4:', type=('build', 'run'))

    depends_on('py-matplotlib@1.5.1:', type=('build', 'run'))
    depends_on('py-seaborn', type=('build', 'run'))
    depends_on('py-scikit-learn', type=('build', 'run'))


