# Copyright 2013-2024 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)


from spack.package import *


class PyAzureCli(PythonPackage):
    """Microsoft Azure Command-Line Tools."""

    homepage = "https://github.com/Azure/azure-cli"
    pypi = "azure-cli/azure-cli-2.9.1.tar.gz"

    license("MIT")

    version(
        "2.9.1",
        sha256="82ddf1cc3050f2f477053fc1cb43aa2647e14483a4355f237f6bd5c81b01592a",
        url="https://pypi.org/packages/3a/c6/61e1b816a87f6b8cd766d5f4be53c15e43430cece1e1be1e23ea4a6e80ff/azure_cli-2.9.1-py3-none-any.whl",
    )

    with default_args(type="run"):
        depends_on("py-antlr4-python3-runtime@4.7.2:4.7", when="@2.4:2.36")
        depends_on("py-azure-batch@9", when="@2.4:2.16")
        depends_on("py-azure-cli-command-modules-nspkg", when="@:2.10")
        depends_on("py-azure-cli-core@2.9.1:2.9", when="@2.9.1:2.9")
        depends_on("py-azure-cli-nspkg@3.0.3:", when="@:2.10")
        depends_on("py-azure-cli-nspkg@2:", when="@:2.10")
        depends_on("py-azure-cosmos@3.0.2:3")
        depends_on("py-azure-datalake-store@0.0.48:", when="@:2.10")
        depends_on("py-azure-functions-devops-build@0.0.22:", when="@:2.29")
        depends_on("py-azure-graphrbac@0.60")
        depends_on("py-azure-keyvault@1.1:1", when="@:2.11")
        depends_on("py-azure-loganalytics", when="@:2.56")
        depends_on("py-azure-mgmt-advisor@2.0.1:2", when="@:2.25")
        depends_on("py-azure-mgmt-apimanagement@:0.1", when="@2.3:2.11")
        depends_on("py-azure-mgmt-appconfiguration@0.4", when="@:2.9")
        depends_on("py-azure-mgmt-applicationinsights@0.1.1:0.1", when="@:2.24")
        depends_on("py-azure-mgmt-authorization@0.52", when="@:2.11")
        depends_on("py-azure-mgmt-batch@9", when="@2.8:2.24")
        depends_on("py-azure-mgmt-batchai@2", when="@:2.26")
        depends_on("py-azure-mgmt-billing@0.2:0", when="@:2.14")
        depends_on("py-azure-mgmt-botservice@0.2", when="@:2.18")
        depends_on("py-azure-mgmt-cdn@4.1:4", when="@:2.9")
        depends_on("py-azure-mgmt-cognitiveservices@6.2", when="@2.8:2.13")
        depends_on("py-azure-mgmt-compute@13", when="@2.9:2.13")
        depends_on("py-azure-mgmt-consumption@2", when="@:2.51")
        depends_on("py-azure-mgmt-containerinstance@1.4:1", when="@:2.27")
        depends_on("py-azure-mgmt-containerregistry@3.0.0-rc14", when="@2.9:2.12")
        depends_on("py-azure-mgmt-containerservice@9.0.1:9.0", when="@2.4:2.11")
        depends_on("py-azure-mgmt-cosmosdb@0.15", when="@2.9:2.11")
        depends_on("py-azure-mgmt-datalake-analytics@0.2.1:0.2", when="@:2.51")
        depends_on("py-azure-mgmt-datalake-store@0.5:0")
        depends_on("py-azure-mgmt-datamigration@:0", when="@:2.17")
        depends_on("py-azure-mgmt-deploymentmanager@0.2:0", when="@:2.45")
        depends_on("py-azure-mgmt-devtestlabs@4", when="@2.6:")
        depends_on("py-azure-mgmt-dns@2.1:2", when="@:2.22")
        depends_on("py-azure-mgmt-eventgrid@3.0.0-rc7", when="@2.9:2.21")
        depends_on("py-azure-mgmt-eventhub@4:4.0", when="@2.8:2.11")
        depends_on("py-azure-mgmt-hdinsight@1.5.1:1.5", when="@2.9")
        depends_on("py-azure-mgmt-imagebuilder@0.4:0", when="@2.8:2.31")
        depends_on("py-azure-mgmt-iotcentral@3:3.0", when="@2.3:2.19")
        depends_on("py-azure-mgmt-iothub@0.12", when="@2.6:2.23")
        depends_on("py-azure-mgmt-iothubprovisioningservices@0.2", when="@:2.27")
        depends_on("py-azure-mgmt-keyvault@2.2:2", when="@2.3:2.10")
        depends_on("py-azure-mgmt-kusto@0.3")
        depends_on("py-azure-mgmt-loganalytics@0.7:0", when="@2.9:2.18")
        depends_on("py-azure-mgmt-managedservices@1")
        depends_on("py-azure-mgmt-managementgroups@:0", when="@:2.33")
        depends_on("py-azure-mgmt-maps@:0.1", when="@:2.26")
        depends_on("py-azure-mgmt-marketplaceordering@:0", when="@:2.21")
        depends_on("py-azure-mgmt-media@2.1:2", when="@2.6:2.19")
        depends_on("py-azure-mgmt-monitor@0.10", when="@2.9")
        depends_on("py-azure-mgmt-msi@0.2:0", when="@:2.34")
        depends_on("py-azure-mgmt-netapp@0.8", when="@2.3:2.9")
        depends_on("py-azure-mgmt-network@11", when="@2.9:2.11")
        depends_on("py-azure-mgmt-policyinsights@0.5", when="@2.9:2.26")
        depends_on("py-azure-mgmt-privatedns@:0", when="@:2.23")
        depends_on("py-azure-mgmt-rdbms@2.2:2", when="@2.3:2.11")
        depends_on("py-azure-mgmt-recoveryservices@0.4", when="@:2.24")
        depends_on("py-azure-mgmt-recoveryservicesbackup@0.6", when="@:2.18")
        depends_on("py-azure-mgmt-redhatopenshift@:0", when="@2.4:2.27")
        depends_on("py-azure-mgmt-redis@7", when="@:2.26")
        depends_on("py-azure-mgmt-relay@:0.1", when="@:2.51")
        depends_on("py-azure-mgmt-reservations@0.6", when="@:2.36")
        depends_on("py-azure-mgmt-search@2", when="@:2.18")
        depends_on("py-azure-mgmt-security@0.4.1:0.4", when="@2.8:2.16")
        depends_on("py-azure-mgmt-servicebus@0.6:0", when="@:2.23")
        depends_on("py-azure-mgmt-servicefabric@0.4", when="@:2.11")
        depends_on("py-azure-mgmt-signalr@0.4:0", when="@2.9:2.24")
        depends_on("py-azure-mgmt-sql@0.19", when="@2.9:2.11")
        depends_on("py-azure-mgmt-sqlvirtualmachine@0.5:0", when="@:2.27")
        depends_on("py-azure-mgmt-storage@11.1", when="@2.9:2.11")
        depends_on("py-azure-mgmt-trafficmanager@0.51:0", when="@:2.32")
        depends_on("py-azure-mgmt-web@0.47", when="@2.9:2.13")
        depends_on("py-azure-multiapi-storage@0.3.2:0.3", when="@2.6:2.10")
        depends_on("py-azure-storage-common@1.4:1", when="@2.9:")
        depends_on("py-cryptography@2.3.1:2", when="@:2.19")
        depends_on("py-fabric@2.4:2", when="@:2.56")
        depends_on("py-javaproperties@0.5.1", when="@:2.28")
        depends_on("py-jsmin@2.2.2:2", when="@:2.28.0")
        depends_on("py-jsondiff@1.2", when="@:2.28")
        depends_on("py-pytz@2019:2019.1", when="@:2.30")
        depends_on("py-scp@0.13.2:0.13")
        depends_on("py-sshtunnel@0.1.4:0.1")
        depends_on("py-urllib3@1.18:1+secure", when="@:2.18")
        depends_on("py-vsts-cd-manager@1.0.2:", when="@:2.25")
        depends_on("py-websocket-client@0.56", when="@:2.34")
        depends_on("py-xmltodict@0.12:")
