#!/bin/bash -e
#
# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

#
# Description:
#     Runs Spack build smoke tests.  This installs a few packages that
#     cover different parts of the build system.  It is not an exhaustive
#     test of Spack's packages.
#
# Usage:
#     run-build-tests
#
. "$(dirname $0)/setup.sh"
check_dependencies ${coverage} git hg svn

# Fetch the sources in a mirror, and add it to Spack
mkdir -p ~/.mirror
bin/spack mirror add travis ~/.mirror
bin/spack mirror create -D -d ~/.mirror ${SPEC}


# Move to root directory of Spack
# Allows script to be run from anywhere
cd "$SPACK_ROOT"

# Make sure we have a spec to build.
if [ -z "$SPEC" ]; then
    echo "Error: run-build-tests requires the $SPEC to build to be set."
    exit 1
fi

if [ "${SPEC}" = "mpich" ] ; then
    OPTIONS="-v"
fi

# Print compiler information
spack config get compilers

# Run some build smoke tests, potentially with code coverage
${coverage_run} bin/spack install ${OPTIONS} ${SPEC}
