#!/bin/bash
#
# This script runs source code style checks on Spack.
#
# To run it, you'll need to have the Python flake8 installed locally.
#
PYTHONPATH=./lib/spack:$PYTHONPATH

flake8="$(which flake8)"
if [[ ! $flake8 ]]; then
    echo "ERROR: flake8 is required to run this script."
    exit 1
fi

# Move to Spack root; allows script to be run from anywhere
cd "$(dirname "$0")/../../.."

# Add changed files that have been committed since branching off of develop
changed=($(git diff --name-only --find-renames develop... -- '*.py'))
# Add changed files that have been staged but not yet committed
changed+=($(git diff --name-only --find-renames --cached -- '*.py'))
# Add changed files that are unstaged
changed+=($(git diff --name-only --find-renames -- '*.py'))

# Ensure that each file in the array is unique
changed=($(printf '%s\n' "${changed[@]}" | sort -u))

function cleanup {
    # Restore original package files after modifying them.
    for file in "${changed[@]}"; do
        if [[ -e "${file}.sbak~" ]]; then
            mv "${file}.sbak~" "${file}"
        fi
    done
}

# Cleanup temporary files upon exit or when script is killed
trap cleanup EXIT SIGINT SIGTERM

# Add approved style exemptions to the changed packages.
for file in "${changed[@]}"; do
    # Make a backup to restore later
    cp "$file" "$file.sbak~"

    #
    # Exemptions for package.py files
    #
    if [[ $file = *package.py ]]; then
        # Exempt lines with urls and descriptions from overlong line errors.
        perl -i -pe 's/^(\s*homepage\s*=.*)$/\1  # NOQA: ignore=E501/' $file
        perl -i -pe 's/^(\s*url\s*=.*)$/\1  # NOQA: ignore=E501/' $file
        perl -i -pe 's/^(\s*version\(.*\).*)$/\1  # NOQA: ignore=E501/' $file
        perl -i -pe 's/^(\s*variant\(.*\).*)$/\1  # NOQA: ignore=E501/' $file
        perl -i -pe 's/^(\s*depends_on\(.*\).*)$/\1  # NOQA: ignore=E501/' $file
        perl -i -pe 's/^(\s*extends\(.*\).*)$/\1  # NOQA: ignore=E501/' $file

        # Exempt '@when' decorated functions from redefinition errors.
        perl -i -pe 's/^(\s*\@when\(.*\).*)$/\1  # NOQA: ignore=F811/' $file
    fi

    #
    # Exemptions for all files
    #
    perl -i -pe 's/^(.*(https?|file)\:.*)$/\1  # NOQA: ignore=E501/' $file
done

if [[ "${changed[@]}" ]]; then
    echo =======================================================
    echo  flake8: running flake8 code checks on spack.
    echo
    echo  Modified files:
    echo  "${changed[@]}" | perl -pe 's/^/  /;s/ +/\n  /g'
    echo =======================================================
    if flake8 --format pylint "${changed[@]}"; then
        echo "Flake8 checks were clean."
    else
        echo "Flake8 found errors."
        exit 1
    fi
else
    echo No core framework files modified.
fi

exit 0
