#!/bin/bash -e
#
# Description:
#     Builds Spack documentation and checks for
#     possible syntax errors. Treats warnings as
#     fatal errors.
#
# Usage:
#     run-doc-tests
#
. "$(dirname $0)/setup.sh"
check_dependencies sphinx-apidoc sphinx-build dot git hg svn

# Move to documentation directory
# Allows script to be run from anywhere
cd "$SPACK_ROOT/lib/spack/docs"

# Treat warnings as fatal errors
make clean --silent
make SPHINXOPTS=-W
