#!/bin/bash -e
#
# Copyright 2013-2019 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

#
# Description:
#     Runs Spack unit tests.
#
# Usage:
#     run-unit-tests [test ...]
#
# Options:
#     Optionally add one or more unit tests
#     to only run these tests.
#
. "$(dirname $0)/setup.sh"
check_dependencies ${coverage} git hg svn

# Move to root directory of Spack
# Allows script to be run from anywhere
cd "$SPACK_ROOT"

# Print compiler information
spack config get compilers

# Run spack help to cover command import
${coverage_run} bin/spack -h
${coverage_run} bin/spack help -a

# Profile and print top 20 lines for a simple call to spack spec
if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then
    ${coverage_run} bin/spack -p --lines 20 spec mpileaks%gcc ^elfutils@0.170
fi

# Run unit tests with code coverage
extra_args=""
if [[ -n "$@" ]]; then
    extra_args="-k $@"
fi
${coverage_run} bin/spack test --verbose "$extra_args"
