#!/bin/bash -e
#
# Copyright 2013-2019 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

#
# Description:
#     Runs Spack docker tests.  This builds a docker image for each of the
#     configurations in share/spack/docker/config.
#
# Usage:
#     run-docker-tests
#

__login_attempted=0
__login_success=1
ensure_docker_login() {
    if [ "$__login_attempted" '!=' '0' ] ; then
        return $__login_success
    fi

    echo "$DOCKER_PASSWORD" | \
        docker login -u "$DOCKER_USERNAME" --password-stdin

    if [ $? '=' '0' ] ; then
          __login_success=0
    fi

    __login_attempted=1
    return $__login_success
}

this_dir=$(cd $(dirname $0) && pwd)
SPACK_BIN="${this_dir}/../../../bin/spack"

# packages.spack.io service
${SPACK_BIN} list --format version_json > ${this_dir}/../packages/packages.json
./share/spack/packages/build-image.sh
if [ "$TEST_SUITE" '=' "docker" -a \
     "$TRAVIS_EVENT_TYPE" != "pull_request" ] && ensure_docker_login ; then
    ./share/spack/packages/push-image.sh
fi

