#!/bin/bash -e
#
# Description:
#     Runs source code style checks on Spack.
#     See $SPACK_ROOT/.flake8 for a list of
#     approved exceptions.
#
# Usage:
#     run-flake8-tests
#
. "$(dirname $0)/setup.sh"
check_dependencies flake8

spack flake8
