#!/bin/bash -e
#
# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

#
# Description:
#     Runs source code style checks on Spack.
#     See $SPACK_ROOT/.flake8 for a list of
#     approved exceptions.
#
# Usage:
#     run-flake8-tests
#
. "$(dirname $0)/setup.sh"

BASE=""
if [ -n "$GITHUB_BASE_REF" ]; then
    BASE="--base ${GITHUB_BASE_REF}"
fi

# verify that the code style is correct
spack style --root-relative $BASE

# verify that the license headers are present
spack license verify
