#!/bin/bash -e
#
# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

#
# Description:
#     Runs source code style checks on Spack.
#     See $SPACK_ROOT/.flake8 for a list of
#     approved exceptions.
#
# Usage:
#     run-flake8-tests
#
. "$(dirname "$0")/setup.sh"

args=()
if [[ -n $GITHUB_BASE_REF ]]; then
    args+=("--base" "${GITHUB_BASE_REF}")
else
    args+=("--base" "${GITHUB_REF_NAME}")
fi

# verify that the code style is correct
spack style --root-relative "${args[@]}"

# verify that the license headers are present
spack license verify
