#!/bin/bash -e
#
# Copyright Spack Project Developers. See COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

#
# Description:
#     Runs Spack shell tests.
#
# Usage:
#     run-shell-tests

#-----------------------------------------------------------
# Run a few initial commands and set up test environment
#-----------------------------------------------------------
echo "Starting run-shell-test"
ORIGINAL_PATH="$PATH"

. "$(dirname $0)/setup.sh"
if [ "$COVERAGE" = true ]; then
  check_dependencies $coverage kcov git hg svn
else
  echo "COVERAGE not set to 'true' [skipping coverage]"
fi
echo "Checked dependencies"

# Clean the environment by removing Spack from the path and getting rid of
# the spack shell function
export PATH="$ORIGINAL_PATH"
unset spack

# Convert QA_DIR to absolute path before changing directory
export QA_DIR=$(realpath $QA_DIR)

echo "Setting env variables"
# Start in the spack root directory
cd "$SPACK_ROOT"

# Run bash tests with coverage enabled, but pipe output to /dev/null
# because it seems that kcov undoes the script's redirection
if [ "$COVERAGE" = true ]; then
    echo "Start running bash test with coverage enabled"
    kcov "$SPACK_ROOT/coverage" "$QA_DIR/setup-env-test.sh" &> /dev/null
    echo "Start running completion-test with coverage"
    kcov "$SPACK_ROOT/coverage" "$QA_DIR/completion-test.sh" &> /dev/null
else
    echo "Start running bash test without coverage"
    bash "$QA_DIR/setup-env-test.sh"
    echo "Start running completion-test"
    bash "$QA_DIR/completion-test.sh"
fi

echo "Run zsh & dash tests"
# Run the test scripts for their output (these will print nicely)
zsh  "$QA_DIR/setup-env-test.sh"
zsh "$QA_DIR/completion-test.sh"
dash "$QA_DIR/setup-env-test.sh"

echo "Run fish test"
# Run fish tests
fish "$QA_DIR/setup-env-test.fish"

echo "Run csh & tsch tests"
# Run csh and tcsh tests
csh  "$QA_DIR/setup-env-test.csh"
tcsh "$QA_DIR/setup-env-test.csh"

echo "Run test-env-cfg.sh"
# check that spack can help users edit an environment's manifest file
# even when it has invalid configuration
sh "$QA_DIR/test-env-cfg.sh"
