# -*- coding: utf-8 -*-
# Copyright Spack Project Developers. See COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
"""This package implements Spack environments.

The format of ``spack.lock`` is documented in :ref:`lockfile-format`.
"""

from .environment import (
    TOP_LEVEL_KEY,
    Environment,
    EnvironmentConcretizer,
    SpackEnvironmentConfigError,
    SpackEnvironmentDevelopError,
    SpackEnvironmentError,
    SpackEnvironmentViewError,
    activate,
    active,
    all_environment_names,
    all_environments,
    as_env_dir,
    create,
    create_in_dir,
    deactivate,
    default_manifest_yaml,
    default_view_name,
    display_specs,
    environment_dir_from_name,
    environment_from_name_or_dir,
    environment_path_scope,
    exists,
    initialize_environment_dir,
    installed_specs,
    is_env_dir,
    is_latest_format,
    lockfile_include_key,
    lockfile_name,
    manifest_file,
    manifest_include_name,
    manifest_name,
    no_active_environment,
    read,
    root,
    spack_env_var,
    spack_env_view_var,
    update_yaml,
)

__all__ = [
    "TOP_LEVEL_KEY",
    "Environment",
    "EnvironmentConcretizer",
    "SpackEnvironmentConfigError",
    "SpackEnvironmentDevelopError",
    "SpackEnvironmentError",
    "SpackEnvironmentViewError",
    "activate",
    "active",
    "all_environment_names",
    "all_environments",
    "as_env_dir",
    "create",
    "create_in_dir",
    "deactivate",
    "default_manifest_yaml",
    "default_view_name",
    "display_specs",
    "environment_dir_from_name",
    "environment_from_name_or_dir",
    "environment_path_scope",
    "exists",
    "initialize_environment_dir",
    "installed_specs",
    "is_env_dir",
    "is_latest_format",
    "lockfile_include_key",
    "lockfile_name",
    "manifest_file",
    "manifest_include_name",
    "manifest_name",
    "no_active_environment",
    "read",
    "root",
    "spack_env_var",
    "spack_env_view_var",
    "update_yaml",
]
