# Copyright Spack Project Developers. See COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
import os
import sys
from datetime import datetime

import spack.environment.shell
import spack.llnl.util.tty as tty
from spack.util.environment import EnvironmentModifications


def path_to_env_activate_shell_script(env, shell: str) -> str:
    """Returns to path to the shell script to activate the specified env for the shell that
    the user is running

    Args:
        env: the environment whose shell script we are returning the path of
        shell: the shell that the user is running
    """
    extension = f".{shell}" if shell == "bat" or shell == "pwsh" else ""
    return os.path.join(env.path, ".spack-env", f"activate{extension}")


def path_to_env_deactivate_shell_script(env, shell: str) -> str:
    """Returns to path to the shell script to activate the specified env for the shell that
    the user is running

    Args:
        env: the environment whose shell script we are returning the path of
        shell: the shell that the user is running
    """

    return os.path.join(env.path, ".spack-env", f"deactivate.{shell}")


def get_shell_unique_env_cmds(shell, prompt: str, view: str) -> str:
    """Returns the prompt, view, and despacktivate commands which are unique
    to each shell

    Args:
        shell: the shell that the user is running
        prompt: name of user's prompt
        view: name of environment's view
    """

    despactivate_cmd = spack.environment.shell.despacktivate_cmds(shell)
    prompt_cmds = spack.environment.shell.activate_prompt_cmds(shell, prompt)
    view_cmd = spack.environment.shell.activate_view_cmds(shell, view)

    cmds = despactivate_cmd + prompt_cmds + view_cmd

    return cmds


def lockfile_newer_than_script(lockfile_date, script_path) -> bool:
    """Returns true if the environment's lockfile has been change more recently than the
    activation or deactivations script

    Args:
        lockfile_date: a timestamp of when the lockfile was last updated
        script_path: a path to the cached activation/deactivation script
    """

    if os.path.isfile(script_path):
        script_path_date = os.stat(script_path).st_mtime
    else:
        return True

    return lockfile_date > script_path_date


def generate_script(shell_script_path: str, mods: str):
    """Helper function to write spec's shell scripts

    Args:
        shell_script_path: Path to the shell script.
        mods: Modifications to write to the script.
    """

    try:
        with open(shell_script_path, "w", encoding="utf-8") as f:
            f.write(
                f"### Script generated by spack (https://github.com/spack/spack) "
                f"{datetime.now().strftime('%Y-%m-%d')}\n\n"
            )
            f.write(mods)
    except OSError as e:
        tty.error(f"Error generating to {shell_script_path}: {e}")


def write_env_activate_script(env, view: str = "default"):
    """Gets and writes the environment modifications for an activated environment to a
    cached shell script

    Args:
        env: the environment the activation script is written for
        view: the name of the environment's view
    """

    shells_avail = ["sh"]  # csh & fish have the same script as sh

    if sys.platform == "win32":
        shells_avail.extend(["bat", "pwsh"])

    for shell in shells_avail:
        env_mods = EnvironmentModifications()

        cmds = spack.environment.shell.activate_commands(env, shell, view)
        cmds += env_mods.shell_modifications(shell)

        activate_script_path = path_to_env_activate_shell_script(env, shell)
        generate_script(activate_script_path, cmds)


def update_env_activate_script(env, view: str = "default"):
    """Overwrite existing environment activation script with new environment modifications

    Args:
        env: the environment the activation script is written for
        view: the name of the environment's view
    """

    shells_avail = ["sh"]  # csh & fish have the same script as sh

    if sys.platform == "win32":
        shells_avail.extend(["bat", "pwsh"])

    # Check if the lockfile exists and get its modification time
    lockfile_date = os.stat(env.lock_path).st_mtime if os.path.isfile(env.lock_path) else 0.00

    for shell in shells_avail:
        env_mods = EnvironmentModifications()
        env_mods.extend(spack.environment.shell.activate(env=env, view=view))

        activate_script_path = path_to_env_activate_shell_script(env, shell)

        # Update the script only if the lockfile doesn't exist or is newer than script
        if lockfile_date == 0.00 or lockfile_newer_than_script(
            lockfile_date, activate_script_path
        ):
            cmds = spack.environment.shell.activate_commands(env, shell, view=view)
            cmds += env_mods.shell_modifications(shell)

            generate_script(activate_script_path, cmds)


def write_env_deactivate_script(env, view: str):
    """Gets and writes the environment modifications to deactivate the specified
    environment to a cached shell script

    Args:
        env: the environment the deactivation script is written for
        view: the name of the environment's view
    """

    shells_avail = ["sh", "csh", "fish"]

    if sys.platform == "win32":
        shells_avail.extend(["bat", "pwsh"])

    # Check if the lockfile exists and get its modification time
    lockfile_date = os.stat(env.lock_path).st_mtime if os.path.isfile(env.lock_path) else 0.00

    for shell in shells_avail:
        deactivate_script_path = path_to_env_deactivate_shell_script(env, shell)

        # Update the script only if the lockfile doesn't exist or is newer than script
        if lockfile_date == 0.00 or lockfile_newer_than_script(
            lockfile_date, deactivate_script_path
        ):
            env_mods = spack.environment.shell.deactivate(env, view)

            cmds = spack.environment.shell.deactivate_commands(shell)
            cmds += env_mods.shell_modifications(shell)

            generate_script(deactivate_script_path, cmds)
