# Copyright Spack Project Developers. See COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
import os
import sys
from datetime import datetime

import spack.environment.shell
import spack.util.filesystem as fs
import spack.util.tty as tty
from spack.util.environment import EnvironmentModifications


def path_to_env_activate_shell_script(env, shell: str) -> str:
    """Returns to path to the shell script to activate the specified env for the shell that
    the user is running

    Args:
        env: the environment whose shell script we are returning the path of
        shell: the shell that the user is running
    """
    extension = ""
    if shell == "bat":
        extension = ".bat"
    elif shell == "pwsh":
        extension = ".ps1"

    return os.path.join(env.path, ".spack-env", f"activate{extension}")


def path_to_env_deactivate_shell_script(env, shell: str) -> str:
    """Returns to path to the shell script to activate the specified env for the shell that
    the user is running

    Args:
        env: the environment whose shell script we are returning the path of
        shell: the shell that the user is running
    """
    extension = shell
    if shell == "bat":
        extension = ".bat"
    elif shell == "pwsh":
        extension = ".ps1"

    return os.path.join(env.path, ".spack-env", f"deactivate.{extension}")


def get_shell_unique_env_cmds(shell, prompt: str, view: str) -> str:
    """Returns the prompt, view, and despacktivate commands which are unique
    to each shell

    Args:
        shell: the shell that the user is running
        prompt: name of user's prompt
        view: name of environment's view
    """

    despactivate_cmd = spack.environment.shell.despacktivate_cmds(shell)
    prompt_cmds = spack.environment.shell.activate_prompt_cmds(shell, prompt)

    cmds = despactivate_cmd + prompt_cmds

    return cmds


def _lockfile_newer_than_script(lockfile_date, script_path) -> bool:
    """Returns true if the environment's lockfile has been change more recently than the
    activation or deactivations script

    Args:
        lockfile_date: a timestamp of when the lockfile was last updated
        script_path: a path to the cached activation/deactivation script
    """

    if os.path.isfile(script_path):
        script_path_date = os.stat(script_path).st_mtime
    else:
        return True

    return lockfile_date > script_path_date


def _generate_script(shell_script_path: str, mods: str, comments: str):
    """Helper function to write spec's shell scripts

    Args:
        shell_script_path: Path to the shell script.
        mods: Modifications to write to the script.
        comments: Comment character(s) to use in the script
            (e.g. "::" for bat and ### for all other shells)
    """

    try:
        header = (
            f"{comments} This file is auto-generated by Spack. Do not edit this file directly.\n"
            f"{comments} Generated on: {datetime.now().strftime('%Y-%m-%d')}\n\n"
        )
        with fs.write_tmp_and_move(shell_script_path, encoding="utf-8") as f:
            f.write(header)
            f.write(mods)
    except OSError as e:
        tty.error(f"Error generating to {shell_script_path}: {e}")


def write_env_activate_script(env: "spack.environment.Environment", view: str = "default"):
    """Gets and writes the environment modifications for an activated environment to a
    cached shell script

    Args:
        env: the environment the activation script is written for
        view: the name of the environment's view
    """

    shells_avail = ["sh"]  # csh & fish have the same script as sh
    comments = "###"

    if sys.platform == "win32":
        shells_avail = ["bat", "pwsh"]

    # ensure .env subdir actually exists as we'll be writing to it
    env.ensure_env_directory_exists(dot_env=True)

    # Check if the lockfile exists and get its modification time
    lockfile_date = os.stat(env.lock_path).st_mtime if os.path.isfile(env.lock_path) else 0.00

    for shell in shells_avail:
        env_mods = EnvironmentModifications()
        env_mods.extend(spack.environment.shell.activate(env=env, view=view))

        activate_script_path = path_to_env_activate_shell_script(env, shell)

        # Update the script only if the lockfile doesn't exist or is newer than script
        if lockfile_date == 0.00 or _lockfile_newer_than_script(
            lockfile_date, activate_script_path
        ):
            cmds = spack.environment.shell.activate_commands(env, view)
            cmds += env_mods.shell_modifications(shell)

            if shell == "bat":
                comments = "::"

            _generate_script(activate_script_path, cmds, comments=comments)


def write_env_deactivate_script(env, view: str):
    """Gets and writes the environment modifications to deactivate the specified
    environment to a cached shell script

    Args:
        env: the environment the deactivation script is written for
        view: the name of the environment's view
    """

    shells_avail = ["sh", "csh", "fish"]
    comments = "###"

    if sys.platform == "win32":
        shells_avail = ["bat", "pwsh"]

    # Check if the lockfile exists and get its modification time
    lockfile_date = os.stat(env.lock_path).st_mtime if os.path.isfile(env.lock_path) else 0.00

    for shell in shells_avail:
        deactivate_script_path = path_to_env_deactivate_shell_script(env, shell)

        # Update the script only if the lockfile doesn't exist or is newer than script
        if lockfile_date == 0.00 or _lockfile_newer_than_script(
            lockfile_date, deactivate_script_path
        ):
            env_mods = spack.environment.shell.deactivate(env, view)

            cmds = spack.environment.shell.deactivate_commands(shell)
            cmds += env_mods.shell_modifications(shell)

            if shell == "bat":
                comments = "::"

            _generate_script(deactivate_script_path, cmds, comments)
