echo "Script 2 starting...."
cd /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DWITH_GZFILEOP -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o example.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/test/example.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o adler32.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/adler32.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o adler32_fold.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/adler32_fold.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o chunkset.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/chunkset.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o compare256.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/compare256.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o compress.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/compress.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o cpu_features.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/cpu_features.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o crc32_braid.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/crc32_braid.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o crc32_braid_comb.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/crc32_braid_comb.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o crc32_fold.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/crc32_fold.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o deflate.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/deflate.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o deflate_fast.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/deflate_fast.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o deflate_huff.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/deflate_huff.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o deflate_medium.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/deflate_medium.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o deflate_quick.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/deflate_quick.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o deflate_rle.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/deflate_rle.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o deflate_slow.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/deflate_slow.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o deflate_stored.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/deflate_stored.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o functable.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/functable.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o infback.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/infback.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o inflate.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/inflate.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o inftrees.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/inftrees.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o insert_string.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/insert_string.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o insert_string_roll.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/insert_string_roll.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o slide_hash.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/slide_hash.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o trees.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/trees.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o uncompr.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/uncompr.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o zutil.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/zutil.c
#make -C arch/x86 x86_features.o
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC  -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o x86_features.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/x86_features.c
#make -C arch/x86 slide_hash_avx2.o
#make -C arch/x86 chunkset_avx2.o
#make -C arch/x86 compare256_avx2.o
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -mavx2 -fno-lto -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o slide_hash_avx2.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/slide_hash_avx2.c
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -mavx2 -fno-lto -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o chunkset_avx2.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/chunkset_avx2.c
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -mavx2 -fno-lto -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o compare256_avx2.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/compare256_avx2.c
#make -C arch/x86 adler32_avx2.o
#make -C arch/x86 adler32_avx512.o
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -mavx2 -fno-lto -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o adler32_avx2.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/adler32_avx2.c
#make -C arch/x86 adler32_avx512_vnni.o
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -mavx512f -mavx512dq -mavx512bw -mavx512vl -mtune=cascadelake -fno-lto -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o adler32_avx512.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/adler32_avx512.c
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -mavx512f -mavx512dq -mavx512bw -mavx512vl -mavx512vnni -mtune=cascadelake -fno-lto -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o adler32_avx512_vnni.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/adler32_avx512_vnni.c
#make -C arch/x86 adler32_sse42.o
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -msse4.2 -fno-lto -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o adler32_sse42.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/adler32_sse42.c
#make -C arch/x86 insert_string_sse42.o
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -msse4.2 -fno-lto -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o insert_string_sse42.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/insert_string_sse42.c
#make[1]: Leaving directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
#make -C arch/x86 chunkset_sse2.o
#make -C arch/x86 compare256_sse2.o
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -msse2 -fno-lto -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o chunkset_sse2.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/chunkset_sse2.c
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -msse2 -fno-lto -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o compare256_sse2.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/compare256_sse2.c
#make -C arch/x86 slide_hash_sse2.o
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -msse2 -fno-lto -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o slide_hash_sse2.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/slide_hash_sse2.c
#make -C arch/x86 adler32_ssse3.o
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -mssse3 -fno-lto -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o adler32_ssse3.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/adler32_ssse3.c
#make -C arch/x86 chunkset_ssse3.o
#make[1]: Leaving directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
#make -C arch/x86 crc32_pclmulqdq.o
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -mssse3 -fno-lto -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o chunkset_ssse3.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/chunkset_ssse3.c
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -mpclmul -msse4.2 -fno-lto -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o crc32_pclmulqdq.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/crc32_pclmulqdq.c
#make -C arch/x86 crc32_vpclmulqdq.o
#make[1]: Leaving directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DWITH_GZFILEOP -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o gzlib.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/gzlib.c
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -mpclmul -msse4.2 -mvpclmulqdq -mavx512f -mavx512f -mavx512dq -mavx512bw -mavx512vl -mtune=cascadelake -fno-lto -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o crc32_vpclmulqdq.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/crc32_vpclmulqdq.c
#make[1]: Leaving directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DWITH_GZFILEOP -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o gzread.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/gzread.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DWITH_GZFILEOP -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o gzwrite.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/gzwrite.c
#make[1]: Leaving directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DWITH_GZFILEOP -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o minigzip.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/test/minigzip.c
#make[1]: Leaving directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
#cp arch/x86/x86_features.o x86_features.o
#cp arch/x86/slide_hash_avx2.o slide_hash_avx2.o
#make[1]: Leaving directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
#cp arch/x86/adler32_avx2.o adler32_avx2.o
#cp arch/x86/adler32_avx512.o adler32_avx512.o
#cp arch/x86/adler32_avx512_vnni.o adler32_avx512_vnni.o
#make[1]: Leaving directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
#cp arch/x86/insert_string_sse42.o insert_string_sse42.o
#cp arch/x86/compare256_sse2.o compare256_sse2.o
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o makefixed.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/tools/makefixed.c
#cp arch/x86/adler32_sse42.o adler32_sse42.o
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o maketrees.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/tools/maketrees.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o makecrct.o /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/tools/makecrct.c
#make[1]: Leaving directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o adler32.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/adler32.c
#make[1]: Leaving directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o adler32_fold.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/adler32_fold.c
#make[1]: Leaving directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o chunkset.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/chunkset.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o compare256.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/compare256.c
#make[1]: Leaving directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o compress.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/compress.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o cpu_features.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/cpu_features.c
#make[1]: Leaving directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o crc32_braid.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/crc32_braid.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o crc32_braid_comb.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/crc32_braid_comb.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o crc32_fold.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/crc32_fold.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o deflate.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/deflate.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o deflate_fast.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/deflate_fast.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o deflate_huff.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/deflate_huff.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o deflate_medium.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/deflate_medium.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o deflate_quick.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/deflate_quick.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o deflate_rle.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/deflate_rle.c
#make[1]: Leaving directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o deflate_slow.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/deflate_slow.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o deflate_stored.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/deflate_stored.c
#make[1]: Leaving directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o functable.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/functable.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o infback.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/infback.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o inflate.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/inflate.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o inftrees.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/inftrees.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o insert_string.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/insert_string.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o insert_string_roll.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/insert_string_roll.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o slide_hash.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/slide_hash.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o trees.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/trees.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o uncompr.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/uncompr.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o zutil.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/zutil.c
#make -C arch/x86 x86_features.lo
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC  -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o x86_features.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/x86_features.c
#make[1]: Leaving directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
#make -C arch/x86 slide_hash_avx2.lo
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -mavx2 -fno-lto -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o slide_hash_avx2.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/slide_hash_avx2.c
#make -C arch/x86 chunkset_avx2.lo
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -mavx2 -fno-lto -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o chunkset_avx2.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/chunkset_avx2.c
#make -C arch/x86 compare256_avx2.lo
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -mavx2 -fno-lto -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o compare256_avx2.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/compare256_avx2.c
#make -C arch/x86 adler32_avx2.lo
#make -C arch/x86 adler32_avx512.lo
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -mavx2 -fno-lto -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o adler32_avx2.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/adler32_avx2.c
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -mavx512f -mavx512dq -mavx512bw -mavx512vl -mtune=cascadelake -fno-lto -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o adler32_avx512.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/adler32_avx512.c
#make -C arch/x86 adler32_avx512_vnni.lo
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -mavx512f -mavx512dq -mavx512bw -mavx512vl -mavx512vnni -mtune=cascadelake -fno-lto -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o adler32_avx512_vnni.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/adler32_avx512_vnni.c
#make -C arch/x86 adler32_sse42.lo
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -msse4.2 -fno-lto -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o adler32_sse42.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/adler32_sse42.c
#make -C arch/x86 insert_string_sse42.lo
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -msse4.2 -fno-lto -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o insert_string_sse42.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/insert_string_sse42.c
#make -C arch/x86 chunkset_sse2.lo
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -msse2 -fno-lto -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o chunkset_sse2.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/chunkset_sse2.c
#make[1]: Leaving directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
#make -C arch/x86 compare256_sse2.lo
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -msse2 -fno-lto -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o compare256_sse2.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/compare256_sse2.c
#make -C arch/x86 slide_hash_sse2.lo
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -msse2 -fno-lto -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o slide_hash_sse2.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/slide_hash_sse2.c
#make -C arch/x86 adler32_ssse3.lo
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -mssse3 -fno-lto -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o adler32_ssse3.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/adler32_ssse3.c
#make[1]: Leaving directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
#make -C arch/x86 chunkset_ssse3.lo
#make -C arch/x86 crc32_pclmulqdq.lo
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -mssse3 -fno-lto -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o chunkset_ssse3.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/chunkset_ssse3.c
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -mpclmul -msse4.2 -fno-lto -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o crc32_pclmulqdq.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/crc32_pclmulqdq.c
#make -C arch/x86 crc32_vpclmulqdq.lo
#make[1]: Entering directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -mpclmul -msse4.2 -mvpclmulqdq -mavx512f -mavx512f -mavx512dq -mavx512bw -mavx512vl -mtune=cascadelake -fno-lto -DPIC -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86 -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o crc32_vpclmulqdq.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86/crc32_vpclmulqdq.c
#make[1]: Leaving directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -DWITH_GZFILEOP -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o gzlib.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/gzlib.c
#make[1]: Leaving directory '/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/arch/x86'
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -DWITH_GZFILEOP -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o gzread.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/gzread.c
/dev/shm/shea9/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -fPIC -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -fno-semantic-interposition -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DPIC -DWITH_GZFILEOP -I/dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src -c -o gzwrite.lo /dev/shm/shea9/tmp/spack-stage/spack-stage-zlib-ng-2.1.6-nafn5kmckv7cx4zyakpd5m2wyxemdnbn/spack-src/gzwrite.c
echo "Script 2 done."
