# Copyright Spack Project Developers. See COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

import glob
import os
import sys
from datetime import datetime
from typing import Tuple

import spack.bootstrap.config
import spack.llnl.util.filesystem as fs
import spack.llnl.util.tty as tty
import spack.repo
import spack.user_environment as uenv


def _get_shell_script_path(spec, shell: str, load: bool) -> str:
    """Returns the path to the shell script to load or unload the specified spec for the shell.

    Args:
        spec: The spec whose shell script we are returning the path of
        shell: The shell that the user is running
        load: Whether to return the path to the load or unload script
    """
    extension = ""
    if shell == "bat":
        extension = ".bat"
    elif shell == "pwsh":
        extension = ".ps1"

    if load:
        return os.path.join(spec.prefix, ".spack", f"load{extension}")
    else:
        return os.path.join(spec.prefix, ".spack", f"unload{extension}")


def path_to_load_shell_script(spec, shell: str) -> str:
    """Returns the path to the shell script to load the specified spec for the shell.

    Args:
        spec: The spec whose shell script we are returning the path of
        shell: The shell that the user is running on
    """
    return _get_shell_script_path(spec, shell, load=True)


def path_to_unload_shell_script(spec, shell: str) -> str:
    """Returns the path to the shell script to unload the specified spec for the shell.

    Args:
        spec: The spec whose shell script we are returning the path of
        shell: The shell that the user is running
    """

    return _get_shell_script_path(spec, shell, load=False)


def generate_script(shell_script_path: str, mods: str, comments: str):
    """Helper function to write spec's shell scripts

    Args:
        shell_script_path: Path to the shell script.
        mods: Modifications to write to the script.
        comments: Comment character(s) to use in the script
            (e.g. "::" for bat and ### for all other shells)
    """

    try:
        # Ensure the parent directory exists
        parent_dir = os.path.dirname(shell_script_path)
        if not os.path.exists(parent_dir):
            os.makedirs(parent_dir)

        header = (
            f"{comments} This file is auto-generated by Spack. Do not edit this file directly.\n"
            f"{comments} Generated on: {datetime.now().strftime('%Y-%m-%d')}\n\n"
        )
        with fs.write_tmp_and_move(shell_script_path, encoding="utf-8") as f:
            f.write(header)
            f.write(mods)
    except OSError as e:
        raise OSError(f"Error generating to {shell_script_path}\n{e}")


def make_repo_path(root):
    """Make a RepoPath from the repo subdirectories in an environment.

    Args:
        root: the root of the environment
    """
    repos = (
        spack.repo.from_path(os.path.dirname(p))
        for p in glob.glob(os.path.join(root, "**", "repo.yaml"), recursive=True)
    )
    return spack.repo.RepoPath(*repos)


def get_environment_modifications(spec, shell, repo=None) -> Tuple[str, str]:
    """Returns both load and unload environment modifications for the spec.
    Args:
        spec: The spec whose environment modifications we are returning
        shell: The shell that the user is running
        repo: (Optional) A repo to use when calculating environment modifications

    Returns:
        tuple: (load_modifications, unload_modifications)
    """
    load_env_mod = uenv.environment_modifications_for_specs(spec, repo=repo)
    unload_env_mod = load_env_mod.reversed()

    load_env_mod.prepend_path(uenv.spack_loaded_hashes_var, spec.dag_hash())
    load_mods = load_env_mod.shell_modifications(shell)

    unload_env_mod.remove_path(uenv.spack_loaded_hashes_var, spec.dag_hash())
    unload_mods = unload_env_mod.shell_modifications(shell)

    return load_mods, unload_mods


def post_install(spec, explicit=None):
    """Creates and writes a cached shell script in for all available shells

    Args:
        spec: The spec the requires the shell scripts
        explicit: (Optional) is the spec explicitly installed by the user
    """

    if spec.external:
        return

    # Skip script generation during bootstrapping
    if spack.bootstrap.config.is_bootstrapping():
        return

    shells_avail = ["sh"]  # csh & fish have the same script as sh
    comments = "###"

    if sys.platform == "win32":
        shells_avail = ["bat", "pwsh"]

    for shell in shells_avail:
        if shell == "bat":
            comments = "::"

        try:
            load_script_path = path_to_load_shell_script(spec, shell)
            unload_script_path = path_to_unload_shell_script(spec, shell)

            spack_dir = os.path.join(spec.prefix, ".spack")
            if not os.path.exists(spack_dir):
                os.makedirs(spack_dir)

            repo_path = make_repo_path(spack_dir)
            cached_repo = repo_path if repo_path and repo_path.repos else None

            # Write shell script to load & unload
            load_mods, unload_mods = get_environment_modifications(spec, shell, cached_repo)
            generate_script(load_script_path, load_mods, comments)
            generate_script(unload_script_path, unload_mods, comments)
        except Exception as e:
            msg = f"Error generating shell scripts for {spec.name} in {shell} shell: {e}"
            tty.warn(msg)
