# Copyright Spack Project Developers. See COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

import glob
import os
import sys
from datetime import datetime

import spack.repo
import spack.user_environment as uenv


def path_to_load_shell_script(spec, shell: str) -> str:
    """Returns the path to the shell script to load the specified spec for the shell.

    Args:
        spec: The spec whose shell script we are returning the path of
        shell: The shell that the user is running on
    """
    extension = ""
    if shell == "bat":
        extension = ".bat"
    elif shell == "pwsh":
        extension = ".ps1"

    return os.path.join(spec.prefix, ".spack", f"load{extension}")


def path_to_unload_shell_script(spec, shell: str) -> str:
    """Returns the path to the shell script to unload the specified spec for the shell.

    Args:
        spec: The spec whose shell script we are returning the path of
        shell: The shell that the user is running
    """
    extension = ""
    if shell == "bat":
        extension = ".bat"
    elif shell == "pwsh":
        extension = ".ps1"

    return os.path.join(spec.prefix, ".spack", f"unload{extension}")


def write_spec_scripts(shell_script_path: str, mods: str, comments: str):
    """Helper function to write spec's shell scripts

    Args:
        shell_script_path: Path to the shell script.
        mods: Modifications to write to the script.
        comments: Comment character(s) to use in the script
            (e.g. "::" for bat and ### for all other shells)
    """

    try:
        with open(shell_script_path, "w", encoding="utf-8") as f:
            f.write(
                f"{comments} Script generated by spack (https://github.com/spack/spack) "
                f"{datetime.now().strftime('%Y-%m-%d')}\n\n"
            )
            f.write(mods)
    except OSError as e:
        raise OSError(f"Error generating to {shell_script_path}\n{e}")


def make_repo_path(root):
    """Make a RepoPath from the repo subdirectories in an environment.

    Args:
        root: the root of the environment
    """
    repos = (
        spack.repo.from_path(os.path.dirname(p))
        for p in glob.glob(os.path.join(root, "**", "repo.yaml"), recursive=True)
    )
    return spack.repo.RepoPath(*repos)


def get_load_environment_modifications(spec, shell, repo=None) -> str:
    """Returns the environment modifications to load the specified spec for the shell.

    Args:
        spec: The spec whose environment modifications we are returning
        shell: The shell that the user is running
        repo: (Optional) A repo to use when calculating environment modifications
    """
    env_mod = uenv.environment_modifications_for_specs(spec, repo=repo)
    env_mod.prepend_path(uenv.spack_loaded_hashes_var, spec.dag_hash())

    return env_mod.shell_modifications(shell)


def get_unload_environment_modifications(spec, shell, repo=None):
    """Returns the environment modifications to unload the specified spec for the shell.

    Args:
        spec: The spec whose environment modifications we are returning
        shell: The shell that the user is running
        repo: (Optional) A repo to use when calculating environment modifications
    """
    env_mod = uenv.environment_modifications_for_specs(spec, repo=repo).reversed()
    env_mod.remove_path(uenv.spack_loaded_hashes_var, spec.dag_hash())

    return env_mod.shell_modifications(shell)


def post_install(spec, explicit=None):
    """Creates and writes a cached shell script in for all available shells

    Args:
        spec: The spec the requires the shell scripts
        explicit: (Optional) is the spec explicitly installed by the user
    """

    if spec.external:
        return

    shells_avail = ["sh"]  # csh & fish have the same script as sh
    comments = "###"

    if sys.platform == "win32":
        shells_avail = ["bat", "pwsh"]

    for shell in shells_avail:
        if shell == "bat":
            comments = "::"

        load_script_path = path_to_load_shell_script(spec, shell)
        unload_script_path = path_to_unload_shell_script(spec, shell)

        repo_path = make_repo_path(os.path.join(spec.prefix, ".spack"))
        cached_repo = repo_path if repo_path.repos else None

        # Write shell script to load
        load_mods = get_load_environment_modifications(spec, shell, cached_repo)
        write_spec_scripts(load_script_path, load_mods, comments)

        # Write shell script to unload
        unload_mods = get_unload_environment_modifications(spec, shell, cached_repo)
        write_spec_scripts(unload_script_path, unload_mods, comments)
