packages:
  # EXTERNALS
  cray-mpich:
    buildable: false
    externals:
    - spec: cray-mpich@8.1.25 %cce@15.0.1
      prefix: /opt/cray/pe/mpich/8.1.25/ofi/cray/10.0
      modules:
      - cray-mpich/8.1.25
  cray-libsci:
    buildable: false
    externals:
    - spec: cray-libsci@23.02.1.1 %cce@15.0.1
      prefix: /opt/cray/pe/libsci/23.02.1.1/CRAY/9.0/x86_64/
      modules:
      - cray-libsci/23.02.1.1