ci:
  pipeline-gen:
  - any-job:
      variables:
        SPACK_TARGET_ARCH: skylake_avx512
  - build-job:
      before_script:
      - - curl -LfsS "https://github.com/JuliaBinaryWrappers/GNUMake_jll.jl/releases/download/GNUMake-v4.3.0+1/GNUMake.v4.3.0.x86_64-linux-gnu.tar.gz" -o gmake.tar.gz
        - printf "fef1f59e56d2d11e6d700ba22d3444b6e583c663d6883fd0a4f63ab8bd280f0f gmake.tar.gz" | sha256sum --check --strict --quiet
        - tar -xzf gmake.tar.gz -C /usr bin/make 2> /dev/null
      tags: ["x86_64_v4"]
