#!/bin/sh
set -xeu

: "${SPACK_ROOT:=$(pwd)}"
: "${BASE_IMG:=gcc:12-bookworm}"
: "${JOBS:=16}"
: "${FULL_ARCH:=linux-spack-x86_64_v3}"
: "${TARGET:=x86_64}"
: "${STAGES:=1 2 3 4}"
: "${FORCE_CMD:=}"
export JOBS FULL_ARCH TARGET FORCE_CMD
mkdir -p "${SPACK_ROOT}/bootstrap"
dkr_run() {
    docker run --rm -it \
        -v "$SPACK_ROOT:/spack" \
        -v "$SPACK_ROOT/bootstrap:/home/$USER/.spack/bootstrap" \
        -v "$SPACK_ROOT/tmp:/tmp" \
        -e SPACK_DISABLE_LOCAL_CONFIG=1 \
        -e SPACK_USER_CACHE_PATH=/tmp/spack \
        -e PATH="/spack/bin:$ADD:$PATH" \
        -e JOBS \
        -e STAGE \
        -e FULL_ARCH \
        -e FORCE_CMD \
        -e TARGET \
        -u "$(id -u):$(id -g)" \
        --volume="/etc/group:/etc/group:ro" \
        --volume="/etc/passwd:/etc/passwd:ro" \
        --volume="/etc/shadow:/etc/shadow:ro" \
        $BASE_IMG \
        "$@"
}

for STAGE in $STAGES ; do
    ADD=""
    if [ "$STAGE" -gt 1 ] ; then
        ADD=/spack/bootstraps/stage$((STAGE - 1))/.spack-env/view/bin
    fi
    export STAGE
    echo arch=$FULL_ARCH
    dkr_run /spack/bootstraps/bootstrap-inner
done
