name: import-check

on:
  workflow_call:

jobs:
  # Check we don't make the situation with circular imports worse
  import-check:
    continue-on-error: true
    runs-on: ubuntu-latest
    env:
      EXCLUDE_PATTERN: '^spack\.(vendor|test)\b'
    steps:
    # PR: use the base of the PR as the old commit
    - name: Checkout PR base commit
      if: github.event_name == 'pull_request'
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      with:
        ref: ${{ github.event.pull_request.base.sha }}
        path: old
    # not a PR: use the previous commit as the old commit
    - name: Checkout previous commit
      if: github.event_name != 'pull_request'
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      with:
        fetch-depth: 2
        path: old
    - name: Checkout previous commit
      if: github.event_name != 'pull_request'
      run: git -C old reset --hard HEAD^

    - name: Checkout new commit
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      with:
        path: new
    - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: pip install -r new/.github/workflows/requirements/import-check/requirements.txt
    - name: Circular import check (without inline imports)
      run: uncycle --exclude "$EXCLUDE_PATTERN" --baseline old/lib/spack/spack new/lib/spack/spack
    - name: Circular import check (with inline imports)
      run: uncycle --exclude "$EXCLUDE_PATTERN" --inline --baseline old/lib/spack/spack new/lib/spack/spack
