name: integration tests

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - develop
      - releases/**

concurrency:
  group: intergrations-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  integration:
    name: integration-build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15-intel, macos-latest, windows-latest]
      fail-fast: true
    steps:
      - name: Fetch Spack
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
            fetch-depth: 1
      - name: Fetch Builtin repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
            fetch-depth: 1
            repository: spack/spack-packages
            path: spackages
      - name: Add builtin with shallow clone
        run: |
          bin/spack repo add --scope=spack ${{ github.workspace }}/spackages/repos/spack_repo/builtin
      - name: "Add Integration test repo"
        run: |
          bin/spack repo add ${{ github.workspace }}/var/spack/test_repos/spack_repo/integration_test
      - name: "Install Clingo Win"
        if: ${{ matrix.os == 'windows-latest' }} 
        run: |
          pip install --upgrade pip clingo
      - name: "Spack install"
        id: install
        run: |
          bin/spack env activate ${{ github.workspace }}/var/spack/test_repos/spack_repo/integration_test/integration_env
          bin/spack compiler find
          bin/spack external find cmake ninja
          bin/spack concretize -U
          bin/spack -dv install --test root
      - name: "Determine failure stage"
        if: always() && (steps.install.outcome == 'failure')
        run: |
          echo "FAILURE_STAGE=$(bin/spack location -S)" >> $GITHUB_ENV
      - name: "Collect failure artifacts"
        if: always() && (steps.install.outcome == 'failure')
        uses: actions/upload-artifact@v4
        with:
          name: "broken-${{ matrix.os }}-stage"
          path: $FAILURE_STAGE