name: integration tests

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - develop
      - releases/**

concurrency:
  group: intergrations-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        timeout_minutes: 3
